# Generated by Django 5.2.3 on 2025-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='garage',
            name='longitude',
        ),
    ]
